### PR TITLE
ref: Use default branch as merge target instead of parent detection

### PR DESCRIPTION
**Pull request by kamilogorek**
This is WiP to fix https://github.com/getsentry/craft/issues/327

We remove automatic branch detection, use the default as the main source of truth, but allow for overriding it through the GH Action input (this needs to be added per repository, inside `.github/workflows/release.yml` in `with` clause).

Related required issues:
https://github.com/getsentry/action-prepare-release/pull/23
https://github.com/getsentry/publish/pull/838

### CODE REVIEW

**Comment by kamilogorek** [comment]
cc @BYK

**Comment by BYK** [comment]
This will require reopening #239. I think we can still consider using `git merge-target` and then find the branch name from there?

**Comment by kamilogorek** [comment]
https://github.com/getsentry/publish/pull/873

**Comment by lobsterkatie** [comment]
> this needs to be added per repository, inside .github/workflows/release.yml in with clause

Specifically what needs to be added? Could you link to an example here for individual repo maintainers to follow?

**Comment by kamilogorek** [comment]
@lobsterkatie I updated the readme yesterday here - https://github.com/getsentry/publish#merge-target

**Pull request merged**
