### PR TITLE
ci(lint): Make lint job work for external contributors

### PR DESCRIPTION
**Pull request by BYK**
Using `pull_request.head.ref` does not work if the PR is made from a fork as the local repo credentials don't work for pulling from remote repos (obviously :D). This PR fixes that.

### CODE REVIEW

**Comment by kamilogorek** [comment]
That linter job is very stubborn :P

**Comment by BYK** [comment]
I'll get this fixed @kamilogorek and then ping you. Sorry for the noise :D

**Comment by BYK** [comment]
@kamilogorek now the only way to see if this works is for you to merge this patch and me submitting another one lol

**Review by kamilogorek — APPROVED** [review]

**Comment by kamilogorek** [comment]
Lets try 👀

**Pull request merged**
