### PR TITLE
ref: Remove @octokit/plugin-retry and rely on our own logic

### PR DESCRIPTION
**Pull request by kamilogorek**
We do already have our own logic implemented here - https://github.com/getsentry/craft/blob/2d8ba63ab9670d9b20c8c9e1a082ab60175c2594/src/targets/github.ts#L297-L333

### CODE REVIEW

**Review by BYK — CHANGES_REQUESTED** [review]
Don't think removing octokit-retry altogether is wise as we rely on that in other places.

The additional logic we have only handles `422` errors specifically which are not handled by `octokit-retry`: https://github.com/getsentry/craft/blob/master/src/targets/github.ts#L297-L333

**Comment by kamilogorek** [comment]
Reached out to GitHub support, let’s put this PR aside for now.

**Comment by mattgauntseo-sentry** [comment]
@kamilogorek is this PR still relevant / worth exploring further?

**Comment by kamilogorek** [comment]
Nope, resolved by https://github.com/getsentry/craft/pull/398
Closed and branch deleted.

**Pull request closed without merging**
